### ISSUE TITLE
Still developed?

### ISSUE THREAD

**Issue by bd8392** [ATM-Consulting/module_wordpress_contact-form-7-to-dolibarr#3]
Hi =) is this plugin still developed? because it was the only one I could find...I use dolibarr for years now, and want to connect it to my wordpress (Version: 11.0.3)

**Comment by jeanfrancoisvarin** [comment]
Likewise... It's probably the only easy way I found to connect both.

**Comment by atm-john** [comment]
We use a custom version for ours needs.
If you want support for this module please contact our customer service at http://www.atm-consulting.fr
